<!DOCTYPE html>
<html lang="en">
  
<!-- Head -->
<head>
  <!-- Meta Tags-->
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="keywords" content="Prismatics, job application, tech, design, recruitment">
  <meta name="description" content="Apply for tech and design roles at Prismatics, an IT startup strengthening its product and design team through tech talent.">
  <meta name="author" content="Prismatics Group Project">
  
  <!-- Title -->
  <title>Job Application | Prismatics</title>

  <!-- Icon | Generated by AI -->
  <link rel="icon" type="image/png" href="images/icon.png">
  <!-- External CSS -->
  <link rel="stylesheet" href="styles/styles.css">
  <!-- External Font -->
  <link href="https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&family=Playfair+Display:wght@400;700&display=swap" rel="stylesheet">

  <!-- Internal CSS example -->
  <style>
    body {
      background-color: #f5f5f5;
    }
  </style>
</head>

<!-- Body -->
<body>

<!-- Header -->
<header id="main-header">
  <div class="header-content">
    <h1>Prismatics Recruitment Portal</h1>
  </div>
  <p id="top-para">Strengthening our product and design team through tech talent</p>
</header>

<!-- Navigation bar -->
<nav>
  <img src="images/logo3.png" alt="Prismatics Logo" title="Prismatic Logo" class="logo">
  <ul class="nav-menu">
    <li><a href="index.html">Home</a></li>
    <li><a href="jobdesc.html">Jobs</a></li>
    <li><a href="apply.php" class="active-link">Apply</a></li>
    <li><a href="about.html">About</a></li>
  </ul>
</nav>

<!-- Main -->
<main>
  <section id="application-section">
    <h2>Job Application Form</h2>
    <p id="introm">👋 We’re excited that you’re here! Please follow the steps below to send us your application. Fields marked with * are required.</p>

    <!-- Main Form Container -->
    <form action="process_eoi.php" method="post" class="form-container" enctype="multipart/form-data" novalidate>

      <!-- Job & Personal Info -->
      <fieldset class="personal_address">
        <legend id="job-personallegend">1) Job & Personal Info</legend>
        <label for="jobref" class="form-label">Job Reference Number *</label>
        <input type="text" id="jobref" class="form-input" name="jobref" pattern="[A-Za-z0-9]{5}" placeholder="PM32X (5 characters)" required>
        <br><br>
        <label for="firstname" class="form-label">First Name *</label>
        <input type="text" id="firstname" class="form-input" name="firstname" maxlength="20" pattern="[A-Za-z]{1,20}" placeholder="Brock" required>
        <br><br>
        <label for="lastname" class="form-label">Last Name *</label>
        <input type="text" id="lastname" class="form-input" name="lastname" maxlength="20" pattern="[A-Za-z]+(?: [A-Za-z]+)*" placeholder="oLee" required>
        <br><br>
        <label for="dob" class="form-label">Date of Birth (dd/mm/yyyy) *</label>
        <input type="text" id="dob" class="form-input" name="dob" pattern="^(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[0-2])/\d{4}$" placeholder="dd/mm/yyyy" required>
        <br><br>
        <fieldset class="form-section">
          <legend>Gender *</legend>
          <input type="radio" id="male" name="gender" value="male" required>
          <label for="male">Male</label>

          <input type="radio" id="female" name="gender" value="female">
          <label for="female">Female</label>

          <input type="radio" id="other" name="gender" value="other">
          <label for="other">Other</label>
        </fieldset>
      </fieldset>

      <!-- Address -->
      <fieldset class="personal_address">
        <legend id="addresslegend">2) Address</legend>
        <label for="street" class="form-label">Street Address *</label>
        <input type="text" id="street" class="form-input" name="street" maxlength="40" placeholder="353 burwood rd" required>
        <br><br>
        <label for="suburb" class="form-label">Suburb/Town *</label>
        <input type="text" id="suburb" class="form-input" name="suburb" maxlength="40" placeholder="hawthorne" required>
        <br><br>
        <label for="state" class="form-label">State *</label>
        <select id="state" class="form-input" name="state" required>
          <option value="">-- Select --</option>
          <option value="VIC">VIC</option>
          <option value="NSW">NSW</option>
          <option value="QLD">QLD</option>
          <option value="NT">NT</option>
          <option value="WA">WA</option>
          <option value="SA">SA</option>
          <option value="TAS">TAS</option>
          <option value="ACT">ACT</option>
        </select>
        <br><br>
        <label for="postcode" class="form-label">Postcode *</label>
        <input type="text" id="postcode" class="form-input" name="postcode" pattern="\d{4}" placeholder="Must be only 4 digits" required>
        <br>
        <p>For candidates outside Australia applying for remote positions</p>
        <label for="country" class="form-label">Country *</label>
        <input type="text" id="country" class="form-input" name="country" maxlength="40" placeholder="Antarctica" required>
        <br><br>
      </fieldset>

      <!-- Skills -->
      <fieldset class="skill-control">
        <legend id="skillslegend">3) Skills</legend>
        <div class="skills-group">
          <p>Please select all skills that apply.</p>
          <label><input type="checkbox" name="skills[]" value="html"> HTML</label>
          <label><input type="checkbox" name="skills[]" value="css"> CSS</label>
          <label><input type="checkbox" name="skills[]" value="javascript"> JavaScript</label>
          <label><input type="checkbox" name="skills[]" value="design"> UI/UX Design</label>
          <label><input type="checkbox" name="skills[]" id="otherskills" value="other"> Other skills…</label>
        </div>
        <p>Rate your skill level for the skills you checked <br>(1 = Beginner, 10 = Expert):</p>
        <label for="htmllevel">HTML:</label>
        <input type="range" id="htmllevel" class="skill-slider" name="htmllevel" min="1" max="10" value="1">
        <br><br>
        <label for="csslevel">CSS:</label>
        <input type="range" id="csslevel" class="skill-slider" name="csslevel" min="1" max="10" value="1">
        <br><br>
        <label for="jslevel">JavaScript:</label>
        <input type="range" id="jslevel" class="skill-slider" name="jslevel" min="1" max="10" value="1">
        <br><br>
        <label for="designlevel">UI/UX Design:</label>
        <input type="range" id="designlevel" class="skill-slider" name="designlevel" min="1" max="10" value="1">
        <br><br>
        <label for="otherskills" class="form-label">Please describe other skills:</label><br>
        <textarea id="otherskills" class="form-input" name="otherskills" rows="4" cols="70"></textarea>
      </fieldset>

      <!-- Contact info -->
      <div class="right-column">
        <fieldset class="width-control">
          <legend id="infolegend">4) Contact Info</legend>
          <label for="email" class="form-label">Email *</label>
          <input type="email" id="email" class="form-input" name="email" placeholder="brockOLee@gmail.com" required>
          <br><br>
          <label for="phone" class="form-label">Phone Number *</label>
          <input type="text" id="phone" class="form-input" name="phone" pattern="\d{8,12}" placeholder="8–12 digits" required>
        </fieldset>
        <br>

        <!-- Working style and Availability -->
        <fieldset class="width-control">
          <legend id="stylelegend">5) Preferred Working Style & Availability</legend>
          <label for="remote">Remote</label>
          <input type="radio" id="remote" name="workstyle" value="remote">        
          <label for="hybrid">Hybrid</label>
          <input type="radio" id="hybrid" name="workstyle" value="hybrid">  
          <label for="office">Office</label>
          <input type="radio" id="office" name="workstyle" value="office">
          <br><br>
          <label for="startdate" class="form-label">Available From:</label>
          <input type="date" id="startdate" class="form-input" name="startdate">
        </fieldset>

        <!-- Resume and Reference -->
        <fieldset class="width-control">
          <legend id="resumelegend">6) Upload Resume & References</legend>

          <label for="resume" class="form-label">Upload Resume (Optional):</label><br>
          <input type="file" id="resume" class="form-input" name="resume" accept=".pdf,.doc,.docx">
          <br><br>
          <label for="references" class="form-label">References (Optional):</label><br>
          <textarea id="references" class="form-input" name="references" rows="5" cols="55" placeholder="Example: Brock Olee, Manager at XYZ Company, BrockOlee@example.com, +61 123 456 789"></textarea>
        </fieldset>
      </div>

      <!-- Stay Connected -->
      <fieldset class="connected">
        <legend>Stay Connected</legend>
        <label for="newsletter" class="form-label">Sign up for our newsletter (optional):</label><br>
        <input type="email" id="newsletter" class="form-input" name="newsletter" placeholder="Enter your email">
      </fieldset>
      <br>

      <!-- Submit/reset -->
      <div class="button-row">
        <button type="submit" class="btn">🚀 Send My Application</button>
        <button type="reset" style="background: #c62828; color: #ffffff; font-weight: bold; border: none; padding: 10px 20px; border-radius: 6px; cursor: pointer; transition: background 0.3s; margin: 10px 0;">Reset Form</button>     
      </div>

    </form>
  </section>
</main>

<!-- Footer -->
<footer>
  <hr id="fotterhr">
  <p id="footerp">
    <a href="https://github.com/105975653/Prismatics_group-project.git" target="_blank">GitHub Repository</a> |
    <a href="https://officialfarhan155.atlassian.net/jira/software/projects/PG/boards/67?atlOrigin=eyJpIjoiMzhlODY4NzlkNjRjNGU2OThlZjA5ZDBlMWUzMTMxNzQiLCJwIjoiaiJ9" target="_blank">Jira</a> |
    <a href="mailto:info@companyname.com">Email Us</a>
  </p>
  <p id="copy">&copy; 2025 Prismatics</p>
</footer>

</body>
</html>
