<!-- Common Footer -->
<footer>
  <hr id="footerhr">
  <p id="footerp">
    <a href="https://github.com/105975653/Prismatics_group-project.git" target="_blank">GitHub Repository</a> |
    <a href="https://officialfarhan155.atlassian.net/jira/software/projects/PG/boards/67?atlOrigin=eyJpIjoiMzhlODY4NzlkNjRjNGU2OThlZjA5ZDBlMWUzMTMxNzQiLCJwIjoiaiJ9" target="_blank">Jira</a> |
    <a href="mailto:info@companyname.com">Email Us</a>
  </p>
  <p id="copy">&copy; 2025 Prismatics</p>
</footer>
