<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Prismatics — a startup strengthening its product and design team through tech talent. Find out about our mission, open roles and how to apply.">
  <meta name="author" content="Prismatics Group Project">
  <!-- Title -->
  <title> Home | Prismatics</title>
  <!-- Icon | Generated by AI -->
  <link rel="icon" type="image/png" href="images/icon.png">


  <!-- External CSS -->
  <link rel="stylesheet" href="styles/styles.css">
    <!-- External Font from Google  -->
  <link href="https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&family=Playfair+Display:wght@400;700&display=swap" rel="stylesheet">



</head>
<body>

  <!-- header -->
  <header>
    <div>
      <h1>Prismatics</h1>
    </div>
    <p id="top-para">Strengthening our product and design team through tech talent</p>
  <!-- Navigation bar -->
  <nav>
    <img src="images/logo3.png" alt="Prismatics Logo" title="The Prismatics Logo" class="logo">
    <ul class="nav-menu">
      <li><a href="index.html" class="active-link">Home</a></li>
      <li><a href="jobdesc.html">Jobs</a></li>
      <li><a href="apply.html">Apply</a></li>
      <li><a href="about.html">About</a></li>
    </ul>
  </nav>
  </header>

  <!-- Main content -->
  <main id="main-content">
    <!-- Welcome section -->
    <section aria-labelledby="welcome-section" class="home-intro">
      <div class="description">
      <h2 id="welcome-section">Welcome to Our Journey</h2>
      <p class="home-para">
        Welcome to Prismatics, a growing IT startup dedicated to creating innovative solutions at the intersection of technology, product, and design. As we expand our product and design team, we’re seeking passionate and talented individuals to join us. At Prismatics, technology is about people — we foster a collaborative, inclusive, and forward-thinking environment where every idea can make an impact. From developing cutting-edge applications to designing user-centric digital experiences, our team thrives on curiosity and problem-solving. Explore our current job openings and discover the opportunities to grow, innovate, and shape the future.
      </p>
      </div>
      <!-- Image 1 | Generated by AI  -->
      <div id="image" class="image-wrapper">
        <img src="images/image1.png" title="Prismatics team" alt="Prismatics Team photo" class="same-size">
      </div>
    </section>

  <!-- Description Section-->
    <section aria-labelledby="description-section" class="home-intro">
      <div class="description">
        <h2 id="description-section">Why Join Prismatics?</h2>
        <p class="home-para">
      Prismatics is a place where your ideas truly matter. We celebrate creativity, encourage innovation, and foster collaboration across our teams. By joining us, you’ll have the chance to work on cutting-edge technology, contribute to user-centric product design, and grow your skills in an inclusive environment. Be part of a team shaping the future of digital experiences, where every project challenges you to learn, create, and make an impact.
        </p>
      </div>
    </section>

  <!-- Flexibility section -->
    <section aria-labelledby="flexibility-section" class="home-intro">
      <div class="description">
        <h2 id="flexibility-section">Flexible Hours and Perks</h2>
        <p class="home-para">
          At Prismatics, we understand that life doesn’t always follow a 9-to-5 schedule. That’s why we offer flexible working hours, so you can balance your professional and personal life effectively. Beyond flexibility, our team enjoys a range of perks including professional development opportunities, wellness programs, team-building events, and access to the latest tools and technologies. 
          We believe that a happy, supported team is a productive team. Whether it’s remote work options, learning stipends, or casual Fridays, our culture is designed to empower you to do your best work while taking care of yourself. Join Prismatics and experience a workplace where flexibility, growth, and well-being are priorities, and where every team member feels valued and motivated.
        </p>
      </div>
      <!-- Image 2 | Generated by AI -->
      <div id="image2" class="image-wrapper">
        <img src="images/image2.png" title="Prismatics team" alt="Prismatics group discussion" class="same-size">
      </div>
    </section>

    <!-- Hiring Section -->
    <section aria-labelledby="hiring-section" class="home-intro">
      <div class="description">
        <h2 id="hiring-section">We’re Hiring!</h2>
        <p class="home-para">
        Prismatics is growing and we’re looking for passionate individuals to join our team.  
        Explore exciting roles in development, design, and technology.  
        Click here to visit <a href="jobdesc.html">job description</a>
        </p>
      </div>
    </section>

  </main>

  <!-- Site footer -->
<footer>
  <hr id="fotterhr">
  <p id="footerp">
    <a href="https://github.com/105975653/Prismatics_group-project.git" target="_blank">GitHub Repository</a> |
    <a href="https://officialfarhan155.atlassian.net/jira/software/projects/PG/boards/67?atlOrigin=eyJpIjoiMzhlODY4NzlkNjRjNGU2OThlZjA5ZDBlMWUzMTMxNzQiLCJwIjoiaiJ9" target="_blank">Jira</a> |
    <a href="mailto:info@companyname.com">Email Us</a>
  </p>
    <p id="copy">&copy; 2025 Prismatics</p>
</footer>
</body>
</html>